version: '3'
services:
  flask:
    build: ./flask
    env_file:
      - ./flask/.env
    ports:
      - 5000:5000

  react:
    build: ./react
    env_file:
      - ./react/.env.local
    ports:
      - 3000:3000
