CREATE DATABASE IF NOT EXISTS fit_track;

USE fit_track;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
  FOREIGN KEY (foods) REFERENCES foods(id)
);

CREATE TABLE IF NOT EXISTS foods (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  calories INT NOT NULL,
  user_id INT NOT NULL,
);

